<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>Brads Local Dev Server</title>
		<!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css"> -->
		<!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css"> -->
		<link href='http://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700&subset=latin,cyrillic-ext,cyrillic' rel='stylesheet' type='text/css'>
		<link href='http://daux.io/themes/daux-blue/css/daux-blue.css' rel='stylesheet' type='text/css'>
	</head>
	<body>

		<a href="https://github.com/justinwalsh/daux.io" target="_blank" id="github-ribbon" class="hidden-print">
			<img src="https://s3.amazonaws.com/github/ribbons/forkme_right_darkblue_121621.png" alt="Fork me on GitHub">
		</a>

		<div class="container-fluid fluid-height wrapper">

			<div class="navbar navbar-fixed-top hidden-print">
				<div class="container-fluid">
					<a class="brand navbar-brand pull-left" href="http://daux.io/index">DAUX.IO</a>
					<p class="navbar-text pull-right">Generated by <a href="http://daux.io">Daux.io</a></p>
				</div>
			</div>

			<div class="row columns content">

				<div class="left-column article-tree col-sm-3 hidden-print">
					
					<!-- For Mobile -->
					<div class="responsive-collapse">
						<button type="button" class="btn btn-sidebar" id="menu-spinner-button">
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
						</button>
					</div>

					<div id="sub-nav-collapse" class="sub-nav-collapse">
						
						<!-- Navigation -->
						<ul class="nav nav-list">
							<li><a href="http://daux.io/Getting_Started">Getting Started</a></li>
							<li>
								<a href="http://daux.io/Examples" class="folder">Examples</a>
								<ul class="nav nav-list">
									<li><a href="http://daux.io/Examples/GitHub_Flavored_Markdown">GitHub Flavored Markdown</a></li>
									<li><a href="http://daux.io/Examples/Code_Highlighting">Code Highlighting</a></li>
								</ul>
							</li>
							<li class="open">
								<a href="#" class="aj-nav folder">More Examples</a>
								<ul class="nav nav-list">
									<li class="active"><a href="http://daux.io/More_Examples/Hello_World">Hello World</a></li>
								</ul>
							</li>
						</ul>

						<div class="well well-sidebar">
							<a href="https://github.com/justinwalsh/daux.io/archive/master.zip" target="_blank">Download</a><br>
							<a href="https://github.com/justinwalsh/daux.io" target="_blank">GitHub Repo</a><br>
							<a href="https://github.com/justinwalsh/daux.io/issues" target="_blank">Help/Support/Bugs</a><br>
							<a href="http://todaymade.com" target="_blank">Made by Todaymade</a><br>
							<a href="#" id="toggleCodeBlockBtn" onclick="toggleCodeBlocks();">Show Code Blocks Inline</a><br>
						</div>

					</div>

				</div>

				<div class="right-column float-view content-area col-sm-9">
					<div class="content-page">
						<article>
							<div class="page-header sub-header clearfix">
								<h1>
									<a href="http://daux.io/More_Examples">More Examples</a>
									<i class="glyphicon glyphicon-chevron-right"></i>
									<a href="http://daux.io/More_Examples/Hello_World">Hello World</a>
								</h1>
								<span style="float: left; font-size: 10px; color: gray;">Sunday, August 10, 2014</span>
								<span style="float: right; font-size: 10px; color: gray;">10:11 PM</span>
							</div>
							@foreach ($blocks as $block)
								{{ $block['html'] }}
							@endforeach
						</article>
					</div>
				</div>

			</div>

		</div>

		<!-- hightlight.js -->
		<!-- <script src="http://daux.io/js/highlight.min.js"></script>
		<script>hljs.initHighlightingOnLoad();</script> -->

		<script src="http://daux.io/js/custom.js"></script>
	</body>
</html>